import type { Metadata } from "next";
import "./globals.css";
import { asap, inconsolata, mavenPro } from "@/fonts/fonts";

export const metadata: Metadata = {
  title: "João Tambue",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${asap.variable} ${inconsolata.variable} ${mavenPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
